# Generated by Django 6.0.3 on 2026-03-12 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_zoho_schema_and_attachments'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='account',
            new_name='accounts_ac_account_0b6f1d_idx',
            old_name='accounts_acco_account_588933_idx',
        ),
        migrations.RenameIndex(
            model_name='account',
            new_name='accounts_ac_account_83ebd8_idx',
            old_name='accounts_acco_account_de6a0c_idx',
        ),
        migrations.RenameIndex(
            model_name='account',
            new_name='accounts_ac_industr_019411_idx',
            old_name='accounts_acco_industr_76e5f2_idx',
        ),
        migrations.RenameIndex(
            model_name='account',
            new_name='accounts_ac_created_25027f_idx',
            old_name='accounts_acco_created_7419b8_idx',
        ),
        migrations.RenameIndex(
            model_name='account',
            new_name='accounts_ac_is_acti_b52bc0_idx',
            old_name='accounts_acco_is_acti_fd2f11_idx',
        ),
        migrations.RenameIndex(
            model_name='accountattachment',
            new_name='accounts_ac_account_b73275_idx',
            old_name='accounts_acco_account_2a7f62_idx',
        ),
    ]
