# Generated by Django 6.0.3 on 2026-03-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='stage',
            field=models.CharField(choices=[('Qualification', 'Qualification'), ('Open', 'Open'), ('Won', 'Won'), ('Lost', 'Lost')], default='Qualification', max_length=50),
        ),
    ]
