# Generated by Django 6.0.3 on 2026-03-12 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_dealstage_rebuild_deal_schema'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='deal',
            new_name='deals_deal_stage_i_9f1e85_idx',
            old_name='deals_deal_stage_id_80e7c8_idx',
        ),
        migrations.RenameIndex(
            model_name='deal',
            new_name='deals_deal_closing_e7bb75_idx',
            old_name='deals_deal_closing_84f637_idx',
        ),
        migrations.RenameIndex(
            model_name='deal',
            new_name='deals_deal_deal_ow_7a67ad_idx',
            old_name='deals_deal_deal_ow_8ccf83_idx',
        ),
        migrations.RenameIndex(
            model_name='deal',
            new_name='deals_deal_account_e1053d_idx',
            old_name='deals_deal_account_b0f2fd_idx',
        ),
        migrations.RenameIndex(
            model_name='deal',
            new_name='deals_deal_created_9d9de4_idx',
            old_name='deals_deal_created_7be7e1_idx',
        ),
        migrations.RenameIndex(
            model_name='deal',
            new_name='deals_deal_is_acti_b6ead4_idx',
            old_name='deals_deal_is_acti_8505bb_idx',
        ),
    ]
