# Generated by Django 6.0.3 on 2026-03-12 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_leadactivity_activities__lead_id_5d0514_idx_and_more'),
        ('contacts', '0001_initial'),
        ('leads', '0004_lead_converted_account_lead_converted_contact_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leadactivity',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='contacts.contact'),
        ),
        migrations.AlterField(
            model_name='leadactivity',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='leads.lead'),
        ),
        migrations.AddIndex(
            model_name='leadactivity',
            index=models.Index(fields=['contact', 'created_at'], name='activities__contact_4907df_idx'),
        ),
    ]
