# Generated by Django 6.0.3 on 2026-03-12 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_accounts_acco_account_588933_idx_accounts_ac_account_0b6f1d_idx_and_more'),
        ('activities', '0003_leadactivity_contact_alter_leadactivity_lead_and_more'),
        ('contacts', '0002_alter_contact_options_remove_contact_owner_and_more'),
        ('leads', '0004_lead_converted_account_lead_converted_contact_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leadactivity',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='accounts.account'),
        ),
        migrations.AddIndex(
            model_name='leadactivity',
            index=models.Index(fields=['account', 'created_at'], name='activities__account_65324d_idx'),
        ),
    ]
