import type { CRMDetailSection, LeadRecord } from "../../../lib/shared/crmTypes";

export const leadSummaryFields: Array<{ key: keyof LeadRecord & string; label: string }> = [
  { key: "leadOwner", label: "Lead Owner" },
  { key: "email", label: "Email" },
  { key: "phone", label: "Phone" },
  { key: "mobile", label: "Mobile" },
  { key: "leadStatus", label: "Lead Status" },
];

export const leadSections: CRMDetailSection<LeadRecord>[] = [
  {
    id: "basic-lead-information-section",
    title: "Basic Lead Information",
    type: "info",
    fields: [
      { key: "leadOwner", label: "Lead Owner" },
      { key: "leadName", label: "Lead Name" },
      { key: "firstName", label: "First Name" },
      { key: "lastName", label: "Last Name" },
      { key: "company", label: "Company" },
      { key: "title", label: "Title" },
      { key: "email", label: "Email" },
      { key: "secondaryEmail", label: "Secondary Email" },
      { key: "phone", label: "Phone" },
      { key: "mobile", label: "Mobile" },
      { key: "leadSource", label: "Lead Source" },
      { key: "leadStatus", label: "Lead Status" },
      { key: "industry", label: "Industry" },
      { key: "annualRevenue", label: "Annual Revenue" },
      { key: "website", label: "Website" },
      { key: "noOfEmployees", label: "No Of Employees" },
      { key: "rating", label: "Rating" },
      { key: "fax", label: "Fax" },
      { key: "createdBy", label: "Created By" },
      { key: "createdAt", label: "Created At" },
      { key: "updatedBy", label: "Updated By" },
      { key: "updatedAt", label: "Updated At" },
    ],
  },
  {
    id: "address-information-section",
    title: "Address Information",
    type: "info",
    fields: [
      { key: "address", label: "Address" },
      { key: "city", label: "City" },
      { key: "state", label: "State" },
      { key: "zipCode", label: "Zip Code" },
      { key: "country", label: "Country" },
    ],
  },
  {
    id: "description-information-section",
    title: "Description Information",
    type: "info",
    fields: [{ key: "description", label: "Description" }],
  },
  { id: "notes-section", title: "Notes", type: "notes" },
  { id: "connected-records-section", title: "Connected Records", type: "connected-records" },
  { id: "cadences-section", title: "Cadences", type: "cadences" },
  { id: "attachments-section", title: "Attachments", type: "attachments" },
  { id: "products-section", title: "Products", type: "products" },
  { id: "open-activities-section", title: "Open Activities", type: "activities-open" },
  { id: "closed-activities-section", title: "Closed Activities", type: "activities-closed" },
  { id: "invited-meetings-section", title: "Invited Meetings", type: "meetings" },
  { id: "emails-section", title: "Emails", type: "emails" },
  { id: "campaigns-section", title: "Campaigns", type: "generic" },
  { id: "social-section", title: "Social", type: "social" },
  { id: "links-section", title: "Links", type: "links" },
];
