# Generated by Django 6.0.3 on 2026-03-12 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0005_leadactivity_deal_and_more'),
        ('contacts', '0002_alter_contact_options_remove_contact_owner_and_more'),
        ('deals', '0004_rename_deals_deal_stage_id_80e7c8_idx_deals_deal_stage_i_9f1e85_idx_and_more'),
        ('leads', '0004_lead_converted_account_lead_converted_contact_and_more'),
        ('notes', '0005_leadnote_deal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign_name', models.CharField(db_index=True, max_length=255)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, db_index=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('expected_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('budgeted_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('expected_response', models.PositiveIntegerField(blank=True, null=True)),
                ('numbers_sent', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('campaign_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_campaigns', to=settings.AUTH_USER_MODEL)),
                ('parent_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_campaigns', to='campaigns.campaign')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_activity_links', to='activities.leadactivity')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_activities', to='campaigns.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='campaigns/')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='campaigns.campaign')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_contacts', to='campaigns.campaign')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_campaign_links', to='contacts.contact')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_deals', to='campaigns.campaign')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_campaign_links', to='deals.deal')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_leads', to='campaigns.campaign')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_campaign_links', to='leads.lead')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_notes', to='campaigns.campaign')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_note_links', to='notes.leadnote')),
            ],
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['campaign_name'], name='campaigns_c_campaig_53af7c_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['campaign_owner'], name='campaigns_c_campaig_69fddf_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['start_date'], name='campaigns_c_start_d_38d2f4_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['created_at'], name='campaigns_c_created_eda2da_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['is_active'], name='campaigns_c_is_acti_7a198a_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaignactivity',
            constraint=models.UniqueConstraint(fields=('campaign', 'activity'), name='campaign_activity_unique'),
        ),
        migrations.AddIndex(
            model_name='campaignattachment',
            index=models.Index(fields=['campaign', 'created_at'], name='campaigns_c_campaig_a78c7d_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaigncontact',
            constraint=models.UniqueConstraint(fields=('campaign', 'contact'), name='campaign_contact_unique'),
        ),
        migrations.AddConstraint(
            model_name='campaigndeal',
            constraint=models.UniqueConstraint(fields=('campaign', 'deal'), name='campaign_deal_unique'),
        ),
        migrations.AddConstraint(
            model_name='campaignlead',
            constraint=models.UniqueConstraint(fields=('campaign', 'lead'), name='campaign_lead_unique'),
        ),
        migrations.AddConstraint(
            model_name='campaignnote',
            constraint=models.UniqueConstraint(fields=('campaign', 'note'), name='campaign_note_unique'),
        ),
    ]
