# Generated by Django 6.0.3 on 2026-03-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_lead_source_alter_lead_lead_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
