# Generated by Django 6.0.3 on 2026-03-11 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('contacts', '0001_initial'),
        ('deals', '0002_deal_amount_alter_deal_stage'),
        ('leads', '0003_lead_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='converted_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_leads', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='lead',
            name='converted_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_leads', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='lead',
            name='converted_deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_leads', to='deals.deal'),
        ),
    ]
