# Generated by Django 6.0.3 on 2026-03-11 09:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_lead_converted_account_lead_converted_contact_and_more'),
        ('notes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='leadnote',
            index=models.Index(fields=['created_at'], name='notes_leadn_created_8de4c4_idx'),
        ),
    ]
