# Generated by Django 6.0.3 on 2026-03-12 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contact_options_remove_contact_owner_and_more'),
        ('leads', '0004_lead_converted_account_lead_converted_contact_and_more'),
        ('notes', '0002_leadnote_notes_leadn_created_8de4c4_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leadnote',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='contacts.contact'),
        ),
        migrations.AlterField(
            model_name='leadnote',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='leads.lead'),
        ),
        migrations.AddIndex(
            model_name='leadnote',
            index=models.Index(fields=['lead', 'created_at'], name='notes_leadn_lead_id_6c20e5_idx'),
        ),
        migrations.AddIndex(
            model_name='leadnote',
            index=models.Index(fields=['contact', 'created_at'], name='notes_leadn_contact_d2a9d1_idx'),
        ),
    ]
