# Generated by Django 6.0.3 on 2026-03-12 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_accounts_acco_account_588933_idx_accounts_ac_account_0b6f1d_idx_and_more'),
        ('contacts', '0002_alter_contact_options_remove_contact_owner_and_more'),
        ('deals', '0004_rename_deals_deal_stage_id_80e7c8_idx_deals_deal_stage_i_9f1e85_idx_and_more'),
        ('leads', '0004_lead_converted_account_lead_converted_contact_and_more'),
        ('notes', '0004_leadnote_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leadnote',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='deals.deal'),
        ),
        migrations.AddIndex(
            model_name='leadnote',
            index=models.Index(fields=['deal', 'created_at'], name='notes_leadn_deal_id_b52296_idx'),
        ),
    ]
